//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebarVisibility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebarVisibility.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Exception message:.
        /// </summary>
        public static string ErrorExceprionMessage {
            get {
                return ResourceManager.GetString("ErrorExceprionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open 3D view.
        /// </summary>
        public static string ErrorOpen3dView {
            get {
                return ResourceManager.GetString("ErrorOpen3dView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some rebar are editable by other users. Failed ro process rebars: .
        /// </summary>
        public static string ErrorRebarsAreEditable {
            get {
                return ResourceManager.GetString("ErrorRebarsAreEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set RebasAsBody. Rebar id:.
        /// </summary>
        public static string ErrorUnableSetBody {
            get {
                return ResourceManager.GetString("ErrorUnableSetBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set RebasIsUnobsqured. Rebar id:.
        /// </summary>
        public static string ErrorUnableSetUnobscured {
            get {
                return ResourceManager.GetString("ErrorUnableSetUnobscured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set a Fine level of detalisation for the view. Please make it manually..
        /// </summary>
        public static string ErrorUnableToSetFineDetailLevel {
            get {
                return ResourceManager.GetString("ErrorUnableToSetFineDetailLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , view name:.
        /// </summary>
        public static string ErrorViewName {
            get {
                return ResourceManager.GetString("ErrorViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Revit 2023 you can use Fine detalization level to set rebar as  solid.
        /// </summary>
        public static string RebarBodyRevit2023 {
            get {
                return ResourceManager.GetString("RebarBodyRevit2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar visibility.
        /// </summary>
        public static string TransactionRebarVIsibility {
            get {
                return ResourceManager.GetString("TransactionRebarVIsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
